# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - bot-youtube

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_77223cf06c454044bf33444376cb8259 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_447d615594ae45a89577247c33c1ffc6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_77223cf06c454044bf33444376cb8259 }}/danielmcondor/youtube-daniel:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bot-youtube'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d02efd302968421ba04df4e36dddb6fa }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_77223cf06c454044bf33444376cb8259 }}/danielmcondor/youtube-daniel:${{ github.sha }}'